# Page settings

languageCode = "en-us"
title = "Curriculum vitae Site"
baseurl = "https://liyra.github.io/Curriculum_Vitae/"
theme = "orbit"
publishDir = "docs"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Alexandre Deneuve curriculum vitae website"
    author = "Alexandre Deneuve"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles-6.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Alexandre Deneuve"
        tagline = "Remote software engineer"
        avatar = "profile.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: alexandre.deneuve@outlook.com"
        title = "alexandre.deneuve"

        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel:+1 438 409 1153"
        title = "+1 438 409 1153"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/alexandre-deneuve-16bb0a25/"
        title = "/in/alexandre-deneuve"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/Liyra"
        title = "Liyra"

        [[params.contact.list]]
        class = "website"
        icon = "fa-pagelines"
        url = "//gw.geneanet.org/alexandredeneuve?lang=en&p=alexandre+benoit+julien&n=deneuve&oc=0"
        title = "alexandredeneuve"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "Engineering degree"
        college = "ESIGELEC"
        dates = "2011 - 2016"

        [[params.education.list]]
        degree = "Exchange semester"
        college = "Åbo Akademi University"
        dates = "2015 - 2015"

        [[params.education.list]]
        degree = "Exchange semester"
        college = "Aarhus Universitet"
        dates = "2014 - 2014"

    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "French"
        level = "Native"

        [[params.language.list]]
        language = "English"
        level = "Professional"

        [[params.language.list]]
        language = "Spanish"
        level = "Basics"

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "Saxophone"

        [[params.interests.list]]
        interest = "Ice skating"

        [[params.interests.list]]
        interest = "Genealogy"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = "Software engineer with 5 years of experience, I work remotely from Canada. I have worked in multiple specialized industries (Finance, Mathematics and Video games) from developing and enhancing existing solution to bringing cloud hosting and best practices to everyone. Eager to learn new technologies, and new languages. Bilingual French / English"

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Online Programmer"
        dates = "Jun 2019 - Present"
        company = "Ubisoft, Montréal, Canada"
        details = "Working on a pipeline solution handling from the creation of a backend service until his deployment in AWS ECS, with a fully fledged monitoring and log integration (Grafana, ELS).\nMaintaining and developing this solution to handle the multiple uses cases of new and old back-end services.\n\nI am also promoting best practices around back-end services projects, such as how to manage efficiently auto-scaling on services, or making sure your design is compatible with micro-services and auto-scaling. I help resolve incidents when needs be, a provide external insight and debugging help on demand.\n\nWriting and planning multiple releases for the team, adapting to newcomers providing help, making sure to close deliverables.\nI upgraded the whole project documentation by working closely with a technical writer, and I interact daily with technical and non-technical people alike.\nI made technical presentations to help other team or new members how to get started in AWS, and how we use it in our case."

        [[params.jobs.list]]
        position = "Software Developer"
        dates = "Feb 2018 - May 2019"
        company = "Expertus Technologies, Montréal, Canada"
        details = "Creation of a serverless web application, with CI/CD pipeline on AWS solutions. R&D software development in Python 3 with Amazon Web Services (Lambda, S3, API Gateway and Route53).\n\nCreation of CI/CD pipeline, monitoring and alerting (Prometheus, Grafana, LogStash) solutions on AWS cluster. DevOps, Kafka, Docker, Jenkins, Kubernetes, Prometheus, ELK, AWS, Spring Boot, Java 8 & Python 3.\n\nMigration WebSphere6 to Jboss/Wildfly, software maintenance on production application IBM WAS/DB2"

        [[params.jobs.list]]
        position = "R&D Software engineer"
        dates = "Jun 2016 - Jan 2018"
        company = "Cosmo Tech, Lyon, France"
        details = "Developer on a desktop application (C++) allowing users to create a model of a complex system, and generate a simulator based on that model. C++11 on windows and linux.\n\nIntegration of simulators into a Java web application, with parallel processing. Java 8, Java EE, Spring Framework and Apache Spark\n\nDevelopment of tools to help with every day development tasks. Scrum method, Atlassian tools and Git versioning system."

        [[params.jobs.list]]
        position = "Intern Software Engineer"
        dates = "Jan 2016 - Jun 2016"
        company = "The Cosmo Company, Lyon, France"
        details = "Code optimization: Refactoring a simulator to improve performances, both in execution time and memory usage, and keeping the same behavior. Heavy usage of C++ metaprogramming."

    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Volunteer experience"
        intro = "Involved in multiple local communities, especially musical bands."

        [[params.projects.list]]
        title = "Union Musicale de Montville"
        url = "https://ummecoledemusique.blogspot.com/"
        tagline = "Member of a local music school for more than 15 years, former member of the board of directors for 3 years."

        [[params.projects.list]]
        title = "Montréal New Horizons Band"
        url = "https://nhmontreal-en.weebly.com/"
        tagline = " Member of this local band to help maintain and organize services, events and more! Member of the board of directors for more than a year."

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "Python"
        level = "98%"

        [[params.skills.list]]
        skill = "Amazon Web Services"
        level = "98%"

        [[params.skills.list]]
        skill = "MySQL, PostgreSQL"
        level = "90%"

        [[params.skills.list]]
        skill = "Java"
        level = "80%"

        [[params.skills.list]]
        skill = "C++"
        level = "80%"

        [[params.skills.list]]
        skill = "Javascript"
        level = "50%"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    #
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = "This website has been generated with Hugo. The theme is called Hugo Orbit Theme."
